# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Roland' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Roland
    pod 'SwiftLint'
    pod 'Firebase/Firestore'
    pod 'FirebaseFirestoreSwift'
    pod 'MessageKit'
    pod 'JGProgressHUD'
    pod 'RealmSwift'
    pod 'SDWebImage'


end
